version: "3"
services:

  caddy:
    image: caddy
    container_name: forum-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/frontend:ro