version: "3"
services:
  caddy:
    image: caddy
    container_name: forum-caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/frontend:ro

  node:
    build: ./backend
    image: forum/backend
    container_name: forum-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:1234@forum-database:5432/db?schema=public&connect_timeout=300
    depends_on:
      - postgres
    profiles:
      - backend
  
  postgres:
    image: postgres
    container_name: forum-database
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "db"
    volumes:
      - ./db:/var/lib/postgresql/data
